// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const getLatestEventsByDrone = `-- name: GetLatestEventsByDrone :one
SELECT drone_id, time, event_type, payload FROM events
WHERE drone_id = $1
ORDER BY time DESC
LIMIT 1
`

func (q *Queries) GetLatestEventsByDrone(ctx context.Context, droneID string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getLatestEventsByDrone, droneID)
	var i Event
	err := row.Scan(
		&i.DroneID,
		&i.Time,
		&i.EventType,
		&i.Payload,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
    drone_id,
    time,
    event_type,
    payload
) VALUES (
    $1, $2, $3, $4
)
`

type InsertEventParams struct {
	DroneID   string
	Time      time.Time
	EventType string
	Payload   json.RawMessage
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.DroneID,
		arg.Time,
		arg.EventType,
		arg.Payload,
	)
	return err
}
