// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
    drone_id,
    time,
    event_type,
    payload
) VALUES (
    $1, $2, $3, $4
)
`

type InsertEventParams struct {
	DroneID   string
	Time      time.Time
	EventType string
	Payload   json.RawMessage
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.DroneID,
		arg.Time,
		arg.EventType,
		arg.Payload,
	)
	return err
}
