// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gps.sql

package db

import (
	"context"
	"time"
)

const getLatestGpsByDrone = `-- name: GetLatestGpsByDrone :one
SELECT drone_id, time, latitude, longitude, altitude, heading, pitch, roll, speed, climb_rate, angular_rate FROM gps
WHERE drone_id = $1
ORDER BY time DESC
LIMIT 1
`

func (q *Queries) GetLatestGpsByDrone(ctx context.Context, droneID string) (Gp, error) {
	row := q.db.QueryRowContext(ctx, getLatestGpsByDrone, droneID)
	var i Gp
	err := row.Scan(
		&i.DroneID,
		&i.Time,
		&i.Latitude,
		&i.Longitude,
		&i.Altitude,
		&i.Heading,
		&i.Pitch,
		&i.Roll,
		&i.Speed,
		&i.ClimbRate,
		&i.AngularRate,
	)
	return i, err
}

const insertGps = `-- name: InsertGps :exec
INSERT INTO gps (
    drone_id,
    time,
    latitude,
    longitude,
    altitude,
    heading,
    pitch,
    roll,
    speed,
    climb_rate,
    angular_rate
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type InsertGpsParams struct {
	DroneID     string
	Time        time.Time
	Latitude    float64
	Longitude   float64
	Altitude    float64
	Heading     float64
	Pitch       float64
	Roll        float64
	Speed       float64
	ClimbRate   float64
	AngularRate float64
}

func (q *Queries) InsertGps(ctx context.Context, arg InsertGpsParams) error {
	_, err := q.db.ExecContext(ctx, insertGps,
		arg.DroneID,
		arg.Time,
		arg.Latitude,
		arg.Longitude,
		arg.Altitude,
		arg.Heading,
		arg.Pitch,
		arg.Roll,
		arg.Speed,
		arg.ClimbRate,
		arg.AngularRate,
	)
	return err
}
