// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: joins.sql

package db

import (
	"context"
	"time"
)

const getActiveDronesPerTimeBucket = `-- name: GetActiveDronesPerTimeBucket :many
SELECT
    time_bucket($1::interval, time) AS bucket,
    COUNT(DISTINCT drone_id)::bigint AS drone_count
FROM gps
WHERE time >= $2 AND time <= $3
GROUP BY bucket
ORDER BY bucket
`

type GetActiveDronesPerTimeBucketParams struct {
	Column1 int64
	Time    time.Time
	Time_2  time.Time
}

type GetActiveDronesPerTimeBucketRow struct {
	Bucket     interface{}
	DroneCount int64
}

func (q *Queries) GetActiveDronesPerTimeBucket(ctx context.Context, arg GetActiveDronesPerTimeBucketParams) ([]GetActiveDronesPerTimeBucketRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveDronesPerTimeBucket, arg.Column1, arg.Time, arg.Time_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveDronesPerTimeBucketRow
	for rows.Next() {
		var i GetActiveDronesPerTimeBucketRow
		if err := rows.Scan(&i.Bucket, &i.DroneCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivityByTimeBucket = `-- name: GetActivityByTimeBucket :many
SELECT
    time_bucket($1::interval, time) AS bucket,
    COUNT(*)::bigint AS count
FROM gps
WHERE time >= $2 AND time <= $3
GROUP BY bucket
ORDER BY bucket
`

type GetActivityByTimeBucketParams struct {
	Column1 int64
	Time    time.Time
	Time_2  time.Time
}

type GetActivityByTimeBucketRow struct {
	Bucket interface{}
	Count  int64
}

func (q *Queries) GetActivityByTimeBucket(ctx context.Context, arg GetActivityByTimeBucketParams) ([]GetActivityByTimeBucketRow, error) {
	rows, err := q.db.QueryContext(ctx, getActivityByTimeBucket, arg.Column1, arg.Time, arg.Time_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActivityByTimeBucketRow
	for rows.Next() {
		var i GetActivityByTimeBucketRow
		if err := rows.Scan(&i.Bucket, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatteryStatsByDrone = `-- name: GetBatteryStatsByDrone :many
SELECT
    drone_id,
    MIN(battery_pct) AS min_pct,
    AVG(battery_pct) AS avg_pct,
    MAX(battery_pct) AS max_pct
FROM state
WHERE time >= $1 AND time <= $2
GROUP BY drone_id
`

type GetBatteryStatsByDroneParams struct {
	Time   time.Time
	Time_2 time.Time
}

type GetBatteryStatsByDroneRow struct {
	DroneID string
	MinPct  interface{}
	AvgPct  float64
	MaxPct  interface{}
}

func (q *Queries) GetBatteryStatsByDrone(ctx context.Context, arg GetBatteryStatsByDroneParams) ([]GetBatteryStatsByDroneRow, error) {
	rows, err := q.db.QueryContext(ctx, getBatteryStatsByDrone, arg.Time, arg.Time_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBatteryStatsByDroneRow
	for rows.Next() {
		var i GetBatteryStatsByDroneRow
		if err := rows.Scan(
			&i.DroneID,
			&i.MinPct,
			&i.AvgPct,
			&i.MaxPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConnectedDroneCount = `-- name: GetConnectedDroneCount :one
WITH latest AS (
    SELECT DISTINCT ON (drone_id) drone_id, connected
    FROM state
    ORDER BY drone_id, time DESC
)
SELECT COUNT(*)::bigint AS count FROM latest WHERE connected = true
`

func (q *Queries) GetConnectedDroneCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getConnectedDroneCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDroneCount = `-- name: GetDroneCount :one
SELECT COUNT(DISTINCT drone_id)::bigint AS count FROM gps
`

func (q *Queries) GetDroneCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDroneCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDroneCountByStatus = `-- name: GetDroneCountByStatus :many
WITH latest AS (
    SELECT DISTINCT ON (drone_id) drone_id, status
    FROM state
    ORDER BY drone_id, time DESC
)
SELECT status, COUNT(*)::bigint AS count
FROM latest
GROUP BY status
`

type GetDroneCountByStatusRow struct {
	Status string
	Count  int64
}

func (q *Queries) GetDroneCountByStatus(ctx context.Context) ([]GetDroneCountByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, getDroneCountByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDroneCountByStatusRow
	for rows.Next() {
		var i GetDroneCountByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventCountByType = `-- name: GetEventCountByType :many
SELECT event_type, COUNT(*)::bigint AS count
FROM events
WHERE time >= $1 AND time <= $2
GROUP BY event_type
ORDER BY count DESC
`

type GetEventCountByTypeParams struct {
	Time   time.Time
	Time_2 time.Time
}

type GetEventCountByTypeRow struct {
	EventType string
	Count     int64
}

func (q *Queries) GetEventCountByType(ctx context.Context, arg GetEventCountByTypeParams) ([]GetEventCountByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getEventCountByType, arg.Time, arg.Time_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventCountByTypeRow
	for rows.Next() {
		var i GetEventCountByTypeRow
		if err := rows.Scan(&i.EventType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByDroneTimeRange = `-- name: GetEventsByDroneTimeRange :many
SELECT drone_id, time, event_type, payload FROM events
WHERE drone_id = $1 AND time >= $2 AND time <= $3
ORDER BY time DESC
`

type GetEventsByDroneTimeRangeParams struct {
	DroneID string
	Time    time.Time
	Time_2  time.Time
}

func (q *Queries) GetEventsByDroneTimeRange(ctx context.Context, arg GetEventsByDroneTimeRangeParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByDroneTimeRange, arg.DroneID, arg.Time, arg.Time_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.DroneID,
			&i.Time,
			&i.EventType,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByTimeRange = `-- name: GetEventsByTimeRange :many
SELECT drone_id, time, event_type, payload FROM events
WHERE time >= $1 AND time <= $2
ORDER BY time DESC
`

type GetEventsByTimeRangeParams struct {
	Time   time.Time
	Time_2 time.Time
}

func (q *Queries) GetEventsByTimeRange(ctx context.Context, arg GetEventsByTimeRangeParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByTimeRange, arg.Time, arg.Time_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.DroneID,
			&i.Time,
			&i.EventType,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGpsByDroneTimeRange = `-- name: GetGpsByDroneTimeRange :many
SELECT drone_id, time, latitude, longitude, altitude, heading, pitch, roll, speed, climb_rate, angular_rate FROM gps
WHERE drone_id = $1 AND time >= $2 AND time <= $3
ORDER BY time ASC
`

type GetGpsByDroneTimeRangeParams struct {
	DroneID string
	Time    time.Time
	Time_2  time.Time
}

func (q *Queries) GetGpsByDroneTimeRange(ctx context.Context, arg GetGpsByDroneTimeRangeParams) ([]Gp, error) {
	rows, err := q.db.QueryContext(ctx, getGpsByDroneTimeRange, arg.DroneID, arg.Time, arg.Time_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gp
	for rows.Next() {
		var i Gp
		if err := rows.Scan(
			&i.DroneID,
			&i.Time,
			&i.Latitude,
			&i.Longitude,
			&i.Altitude,
			&i.Heading,
			&i.Pitch,
			&i.Roll,
			&i.Speed,
			&i.ClimbRate,
			&i.AngularRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestGpsAllDrones = `-- name: GetLatestGpsAllDrones :many
SELECT DISTINCT ON (drone_id) drone_id, time, latitude, longitude, altitude, heading, pitch, roll, speed, climb_rate, angular_rate
FROM gps
ORDER BY drone_id, time DESC
`

func (q *Queries) GetLatestGpsAllDrones(ctx context.Context) ([]Gp, error) {
	rows, err := q.db.QueryContext(ctx, getLatestGpsAllDrones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gp
	for rows.Next() {
		var i Gp
		if err := rows.Scan(
			&i.DroneID,
			&i.Time,
			&i.Latitude,
			&i.Longitude,
			&i.Altitude,
			&i.Heading,
			&i.Pitch,
			&i.Roll,
			&i.Speed,
			&i.ClimbRate,
			&i.AngularRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestGpsAndStatePerDrone = `-- name: GetLatestGpsAndStatePerDrone :many
WITH latest_gps AS (
    SELECT DISTINCT ON (drone_id)
        drone_id, time, latitude, longitude, altitude, heading, pitch, roll, speed, climb_rate, angular_rate
    FROM gps
    ORDER BY drone_id, time DESC
),
latest_state AS (
    SELECT DISTINCT ON (drone_id)
        drone_id, time, status, battery_pct, voltage, connected, flight_mode
    FROM state
    ORDER BY drone_id, time DESC
)
SELECT
    g.drone_id,
    g.time AS gps_time,
    g.latitude,
    g.longitude,
    g.altitude,
    g.heading,
    g.pitch,
    g.roll,
    g.speed,
    g.climb_rate,
    g.angular_rate,
    s.time AS state_time,
    s.status,
    s.battery_pct,
    s.voltage,
    s.connected,
    s.flight_mode
FROM latest_gps g
JOIN latest_state s ON g.drone_id = s.drone_id
`

type GetLatestGpsAndStatePerDroneRow struct {
	DroneID     string
	GpsTime     time.Time
	Latitude    float64
	Longitude   float64
	Altitude    float64
	Heading     float64
	Pitch       float64
	Roll        float64
	Speed       float64
	ClimbRate   float64
	AngularRate float64
	StateTime   time.Time
	Status      string
	BatteryPct  float64
	Voltage     float64
	Connected   bool
	FlightMode  string
}

func (q *Queries) GetLatestGpsAndStatePerDrone(ctx context.Context) ([]GetLatestGpsAndStatePerDroneRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestGpsAndStatePerDrone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestGpsAndStatePerDroneRow
	for rows.Next() {
		var i GetLatestGpsAndStatePerDroneRow
		if err := rows.Scan(
			&i.DroneID,
			&i.GpsTime,
			&i.Latitude,
			&i.Longitude,
			&i.Altitude,
			&i.Heading,
			&i.Pitch,
			&i.Roll,
			&i.Speed,
			&i.ClimbRate,
			&i.AngularRate,
			&i.StateTime,
			&i.Status,
			&i.BatteryPct,
			&i.Voltage,
			&i.Connected,
			&i.FlightMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestStateAllDrones = `-- name: GetLatestStateAllDrones :many
SELECT DISTINCT ON (drone_id) drone_id, time, status, battery_pct, voltage, connected, flight_mode
FROM state
ORDER BY drone_id, time DESC
`

func (q *Queries) GetLatestStateAllDrones(ctx context.Context) ([]State, error) {
	rows, err := q.db.QueryContext(ctx, getLatestStateAllDrones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []State
	for rows.Next() {
		var i State
		if err := rows.Scan(
			&i.DroneID,
			&i.Time,
			&i.Status,
			&i.BatteryPct,
			&i.Voltage,
			&i.Connected,
			&i.FlightMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentEvents = `-- name: GetRecentEvents :many
SELECT drone_id, time, event_type, payload FROM events
ORDER BY time DESC
LIMIT $1
`

func (q *Queries) GetRecentEvents(ctx context.Context, limit int32) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getRecentEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.DroneID,
			&i.Time,
			&i.EventType,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStateByDroneTimeRange = `-- name: GetStateByDroneTimeRange :many
SELECT drone_id, time, status, battery_pct, voltage, connected, flight_mode FROM state
WHERE drone_id = $1 AND time >= $2 AND time <= $3
ORDER BY time ASC
`

type GetStateByDroneTimeRangeParams struct {
	DroneID string
	Time    time.Time
	Time_2  time.Time
}

func (q *Queries) GetStateByDroneTimeRange(ctx context.Context, arg GetStateByDroneTimeRangeParams) ([]State, error) {
	rows, err := q.db.QueryContext(ctx, getStateByDroneTimeRange, arg.DroneID, arg.Time, arg.Time_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []State
	for rows.Next() {
		var i State
		if err := rows.Scan(
			&i.DroneID,
			&i.Time,
			&i.Status,
			&i.BatteryPct,
			&i.Voltage,
			&i.Connected,
			&i.FlightMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
