// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"
)

type Event struct {
	DroneID   string
	Time      time.Time
	EventType string
	Payload   json.RawMessage
}

type Gp struct {
	DroneID     string
	Time        time.Time
	Latitude    float64
	Longitude   float64
	Altitude    float64
	Heading     float64
	Pitch       float64
	Roll        float64
	Speed       float64
	ClimbRate   float64
	AngularRate float64
}

type State struct {
	DroneID    string
	Time       time.Time
	Status     string
	BatteryPct float64
	Voltage    float64
	Connected  bool
	FlightMode string
}
