// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: state.sql

package db

import (
	"context"
	"time"
)

const insertState = `-- name: InsertState :exec
INSERT INTO state (
    drone_id,
    time,
    status,
    battery_pct,
    voltage,
    connected,
    flight_mode
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type InsertStateParams struct {
	DroneID    string
	Time       time.Time
	Status     string
	BatteryPct float64
	Voltage    float64
	Connected  bool
	FlightMode string
}

func (q *Queries) InsertState(ctx context.Context, arg InsertStateParams) error {
	_, err := q.db.ExecContext(ctx, insertState,
		arg.DroneID,
		arg.Time,
		arg.Status,
		arg.BatteryPct,
		arg.Voltage,
		arg.Connected,
		arg.FlightMode,
	)
	return err
}
